GET http://localhost:8081/login?data=we1MRfXbSLyNydfDF/dhbgRgBzH/qrojgh2Y8GV2QJA=&password=jjss2223kl
Accept: application/json

###
GET http://localhost:8081/rent/getRoomOverview
Accept: application/json

###
GET http://localhost:8081/rent/getRoomByCommunity?community=湖口社区
Accept: application/json

###