GET http://localhost:8081/DBBackup
Accept: application/json

###
POST http://localhost:8081/updateOrAdd
Content-Type: application/json

{
  "dataCode": 111,
  "opcode": "成功",
  "data": null,
  "other": null
}

###
